rubyweb/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :arreglos

  root :to=> 'welcome#index'
  get ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'
end

rubyweb/app/models/arreglo.rb
class Arreglo < ActiveRecord::Base
end

rubyweb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rubyweb/app/controllers/arreglos_controller.rb
class ArreglosController < ApplicationController
  ActionController::Parameters.permit_all_parameters = true
  before_action :set_arreglo, only: [:show, :edit, :update, :destroy]

  # GET /arreglos
  # GET /arreglos.json
  def index
    @arreglos = Arreglo.all
  end

  # GET /arreglos/1
  # GET /arreglos/1.json
  def show
  end

  # GET /arreglos/new
  def new
    @arreglo = Arreglo.new
  end

  # GET /arreglos/1/edit
  def edit
  end

  # POST /arreglos
  # POST /arreglos.json
  def create
    File.open('/home/vasco/Escritorio/Lab2SD/rubyweb/app/controllers/text.txt', 'r') do |f|
    	while line = f.gets
        @arreglo = Arreglo.new(params = ActionController::Parameters.new(numero: line)  )
        @arreglo.save
	end
        @arreglo.save
        respond_to do |format|
      if @arreglo.save
        format.html { redirect_to @arreglo, notice: 'Arreglo was successfully created.' }
        format.json { render :show, status: :created, location: @arreglo }
      else
        format.html { render :new }
        format.json { render json: @arreglo.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # PATCH/PUT /arreglos/1
  # PATCH/PUT /arreglos/1.json
  def update
    respond_to do |format|
      if @arreglo.update(arreglo_params)
        format.html { redirect_to @arreglo, notice: 'Arreglo was successfully updated.' }
        format.json { render :show, status: :ok, location: @arreglo }
      else
        format.html { render :edit }
        format.json { render json: @arreglo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arreglos/1
  # DELETE /arreglos/1.json
  def destroy
    @arreglo.destroy
    respond_to do |format|
      format.html { redirect_to arreglos_url, notice: 'Arreglo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arreglo
      @arreglo = Arreglo.find(params[:id])
    end
    def arreglo_params
      params.require(:arreglo).permit(:numero)
    end
end

rubyweb/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
#http://sandmoose.com/page/5
def partition_array(array, left, right, pivot_index)
  pivot_value = array[pivot_index]
  array[pivot_index], array[right] = array[right], array[pivot_index]
  store_index = left

  (left..right-1).each do |i|
    if array[i] < pivot_value
      array[i], array[store_index] = array[store_index], array[i]
      store_index = store_index + 1
    end
  end

  array[store_index], array[right] = array[right], array[store_index]
  return store_index
end

def inplace_quicksort(array, left, right)
  if left < right
    pivot_index = (left + ((right - left) / 2)).to_i
    new_pivot_index = partition_array(array, left, right, pivot_index)
    inplace_quicksort(array, left, new_pivot_index - 1)
    inplace_quicksort(array, new_pivot_index + 1, right)
  end

  return array
end

#BubbleSort http://www.sitepoint.com/sorting-algorithms-ruby
def bubble_sort(array)
  n = array.length
  loop do
    swapped = false

    (n-1).times do |i|
      if array[i] > array[i+1]
        array[i], array[i+1] = array[i+1], array[i]
        swapped = true
      end
    end

    break if not swapped
  end

  array
end

#MergeSort http://www.sitepoint.com/sorting-algorithms-ruby
def mergesort(array)
  def merge(left_sorted, right_sorted)
    res = []
    l = 0
    r = 0
 
    loop do
      break if r >= right_sorted.length and l >= left_sorted.length
 
      if r >= right_sorted.length or (l < left_sorted.length and left_sorted[l] < right_sorted[r])
        res << left_sorted[l]
        l += 1
      else
        res << right_sorted[r]
        r += 1
      end
    end
 
    return res
  end
 
  def mergesort_iter(array_sliced)
    return array_sliced if array_sliced.length <= 1
 
    mid = array_sliced.length/2 - 1
    left_sorted = mergesort_iter(array_sliced[0..mid])
    right_sorted = mergesort_iter(array_sliced[mid+1..-1])
    return merge(left_sorted, right_sorted)
  end
 
  mergesort_iter(array)
end
  def index
    response = HTTParty.get("http://localhost:8080/arreglo", :query => {:oauth_token => "abc"})
json = JSON.parse(response.body)
names=json["arreglo"][0]
if json["metodo"]=="quicksort"
	sorted_names = inplace_quicksort(names, 0, names.length - 1)
end
if json["metodo"]=="bubblesort"
	sorted_names=bubble_sort(names)
end
if json["metodo"]=="mergesort"
	sorted_names=mergesort(names)
end
File.open('/home/vasco/Escritorio/Lab2SD/rubyweb/app/controllers/text.txt', 'w') do |f|
  f.puts sorted_names
end 
  end
end

rubyweb/app/helpers/application_helper.rb
module ApplicationHelper
end

rubyweb/app/helpers/arreglos_helper.rb
module ArreglosHelper
end

rubyweb/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rubyweb/app/views/arreglos/_form.html.erb
<%= form_for(@arreglo) do |f| %>
  <% if @arreglo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@arreglo.errors.count, "error") %> prohibited this arreglo from being saved:</h2>

      <ul>
      <% @arreglo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rubyweb/app/views/arreglos/edit.html.erb
<h1>Editing Arreglo</h1>

<%= render 'form' %>

<%= link_to 'Show', @arreglo %> |
<%= link_to 'Back', arreglos_path %>

rubyweb/app/views/arreglos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Arreglos</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arreglos.each do |arreglo| %>
      <tr>
        <td><%= arreglo.numero %></td>
        <td><%= link_to 'Show', arreglo %></td>
        <td><%= link_to 'Edit', edit_arreglo_path(arreglo) %></td>
        <td><%= link_to 'Destroy', arreglo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arreglo', new_arreglo_path %>

rubyweb/app/views/arreglos/new.html.erb
<h1>New Arreglo</h1>

<%= render 'form' %>

<%= link_to 'Back', arreglos_path %>

rubyweb/app/views/arreglos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @arreglo.numero %>
</p>

<%= link_to 'Edit', edit_arreglo_path(@arreglo) %> |
<%= link_to 'Back', arreglos_path %>

rubyweb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rubyweb/app/views/welcome/index.html.erb
<h1>Web Service Ruby Sistemas Distribuidos</h1>
<li id="Arreglo"><a href="http://192.168.43.138:3000/arreglos">Arreglo</a></li